name: update-dependents
on: [push]

jobs:
  update-dependets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone mateusfg7Studies/use-module repo
        run: git clone https://github.com/mateusfg7Studies/use-modules
      - name: Tets if is in the correct repo
        run: |
          pwd
          ls
          #      - run: git submodule update --init --recursive
          #      - run: git submodule update --remote use-as-module
          #      - run: git add .
          #      - run: git status #git commit -m "Update Submodule: use-as-module"
          #      - run: git push
