name: update-dependents
on: [push]

jobs:
  update-dependets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: mateusfg7Studies/use-modules
          token: ${{ secrets.MY_SECRET }}
          submodules: recursive


      - name: Config Git
        run: |
          git config --global user.email "mateusfelipefg77@gmail.com"
          git config --global user.name "mateusfg7"

      - name: Update remotly submodules
        run: git submodule update --remote use-as-module

      - name: Add and commit changed files
        working-directory: use-modules
        run: |
          git add .
          git commit -m "Update Submodule: use-as-module"
      
      #- name: See Logs
        #working-directory: use-modules
        #run: git log --oneline
      - run: pwd && ls
      - run: git status
